repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-ast
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black
